#index:
#    path: /admin
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin
    permanent: true
