language: generic

services:
  - docker

branches:
  only:
    - master

stages:
  - name: build
    if: branch = master AND type = push
    script:
      - docker build -t lissenburg/lissenburg-site-client ./client
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - docker push lissenburg/lissenburg-site-client
  - name: build
    if: branch = master AND type = push
