language: generic

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_2054bb94132c_key -iv $encrypted_2054bb94132c_iv -in ./deploy/travis/travis_deploy_key.enc -out ./deploy/travis/travis_deploy_key -d
  - eval "$(ssh-agent)"
  - chmod 600 ./deploy/travis/travis_deploy_key
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy/travis/travis_deploy_key

deploy:
  provider: script
  script: bash ./deploy/vps/deploy.sh
  on:
    branch: master
