version: '3.7'

services:
  traefik:
    image: traefik:v2.0
    command: --providers.docker --providers.docker.exposedByDefault=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    deploy:
      placement:
        constraints:
          - node.role == manager

  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql:cached
    networks:
      - mysql
    deploy:
      placement:
        constraints:
          - node.role == manager

  client:
    image: lissenburg/lissenburg-client
    deploy:
      labels:
        - traefik.http.routers.lissenburg_client.rule=Host(`lissenburg.dev`)
        - traefik.enable=true
        - traefik.http.routers.lissenburg_client.tls=true
        - traefik.http.routers.lissenburg_client.tls.certresolver=lissenburg_resolver
        - traefik.http.services.lissenburg_client.loadbalancer.server.port=80

  admin_nginx:
    image: lissenburg/admin-nginx
    networks:
      - proxy
      - admin
    deploy:
      labels:
        - traefik.http.routers.lissenburg_admin.rule=Host(`admin.lissenburg.dev`)
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.lissenburg_admin.tls=true
        - traefik.http.routers.lissenburg_admin.tls.certresolver=lissenburg_resolver
        - traefik.http.services.lissenburg_admin.loadbalancer.server.port=80

  admin_php-fpm:
    image: lissenburg/admin-php-fpm
    networks:
      admin:
        aliases:
          - php-fpm
      mysql:


networks:
  proxy:
    name: proxy
    driver: bridge
  mysql:
    name: mysql
    driver: bridge
  admin:
    name: admin
    driver: bridge

volumes:
  mysql_data:
    name: mysql_data
