version: '3.7'

services:
  traefik:
    image: traefik:v2.0
    command: --providers.docker --providers.docker.exposedByDefault=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.role == manager

  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql:cached
    networks:
      - mysql
    deploy:
      placement:
        constraints:
          - node.role == manager

  website_nginx:
    image: lissenburg/website-nginx
    networks:
      - proxy
      - website
    deploy:
      labels:
        - traefik.http.routers.lissenburg_website.rule=Host(`lissenburg.dev`)
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.lissenburg_website.tls=true
        - traefik.http.routers.lissenburg_website.tls.certresolver=lissenburg_resolver
        - traefik.http.services.lissenburg_website.loadbalancer.server.port=80

  website_php-fpm:
    image: lissenburg/website-php-fpm
    environment:
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - FOOBAR=test
    networks:
      website:
        aliases:
          - website-php-fpm-service
      mysql:

networks:
  proxy:
    driver: overlay
  mysql:
    driver: overlay
    attachable: true
  website:
    attachable: true
    driver: overlay

volumes:
  mysql_data:
