entryPoints:
  web:
    address: ':80'

  websecure:
    address: ':443'

certificatesResolvers:
  lissenburg_resolver:
    acme:
      email: sanderlissenburg@gmail.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

providers:
  docker:
    swarmMode: true
