apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-pv
spec:
  storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/data/lissenburg-website"
